version: '2'
services:
  # Mysql Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=root"
      - "TZ=Asia/Jakarta"
    ports:
      - 3306:3306

volumes:
  dbdata:
